# -*- coding: utf-8 -*-
"""Module1_Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlQlj6ghb0OWz6wsuvyOPIsNdvjjA54f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import zipfile

with zipfile.ZipFile("/content/wine-reviews.zip", "r") as zip_ref:
    zip_ref.extractall("/content/")

df1 = pd.read_csv("/content/winemag-data-130k-v2.csv")
df2 = pd.read_csv("/content/winemag-data_first150k.csv")

print(df1.shape)
print(df2.shape)

df1.head()
df2.head()

df1.info()
df2.info()

df1

df2

df = pd.concat([df1, df2], ignore_index=True)

print(df.shape)

df

df = df.drop_duplicates()
print(df.shape)

df

# Checking missing values
df.isnull().sum()

# cleaning the data
df["price"] = df["price"].fillna(df["price"].median())
df["country"] = df["country"].fillna("Unknown")
df["province"] = df["province"].fillna("Unknown")

df

df.describe()

plt.figure()
sns.histplot(df["points"], bins=20)
plt.title("Distribution of Wine Ratings")
plt.show()

plt.figure()
sns.histplot(df["price"], bins=50)
plt.title("Price Distribution")
plt.show()

top_countries = df["country"].value_counts().head(10)

plt.figure()
top_countries.plot(kind="bar")
plt.title("Top Wine Producing Countries")
plt.show()

plt.figure()
sns.scatterplot(x="price", y="points", data=df)
plt.title("Price vs Rating")
plt.show()

correlation = df[["price", "points"]].corr()

sns.heatmap(correlation, annot=True)
plt.title("Correlation Matrix")
plt.show()

country_rating = df.groupby("country")["points"].mean().sort_values(ascending=False).head(10)

country_rating.plot(kind="bar")
plt.title("Average Rating by Country")
plt.show()

df["price_category"] = pd.cut(
    df["price"], bins=[0, 20, 50, 100, 500], labels=["Cheap", "Affordable", "Expensive", "Luxury"]
)

df["price_category"].value_counts().plot(kind="bar")
plt.title("Wine Price Categories")
plt.show()

df.to_csv("cleaned_wine_data.csv", index=False)

from google.colab import files

files.download("cleaned_wine_data.csv")
